### ISSUE TITLE
textDocument/definition may throw an exception

### ISSUE THREAD

**Issue by rwols** [muffinmad/anakin-language-server#6]
Perhaps the text sync goes out of sync, I'm not entirely sure why this happens.

Some relevant logs:

```
:: --> anakin textDocument/definition(302): {'position': {'line': 64, 'character': 43}, 'textDocument': {'uri': 'file:///home/raoul/.config/sublime-text-3/Packages/LSP/tests/test_configurations.py'}}
anakin: ERROR:pygls.protocol:Failed to handle request 302 textDocument/definition Object(position=Object(line=64, character=43), textDocument=Object(uri='file:///home/raoul/.config/sublime-text-3/Packages/LSP/tests/test_configurations.py'))
:: <<< anakin 302: ValueError: `column` parameter (43) is not in a valid range (0-8) for line 65 ('        \n').
anakin: Traceback (most recent call last):
anakin: File "/home/raoul/.local/lib/python3.7/site-packages/pygls/protocol.py", line 325, in _handle_request
anakin: self._execute_request(msg_id, handler, params)
anakin: File "/home/raoul/.local/lib/python3.7/site-packages/pygls/protocol.py", line 250, in _execute_request
anakin: self._send_response(msg_id, handler(params))
anakin: File "/home/raoul/.local/lib/python3.7/site-packages/anakinls/server.py", line 312, in definition
anakin: defs = script.goto(params.position.line + 1, params.position.character)
anakin: File "/home/raoul/.local/lib/python3.7/site-packages/jedi/api/helpers.py", line 464, in wrapper
anakin: column, line_len, line, line_string))
anakin: ValueError: `column` parameter (43) is not in a valid range (0-8) for line 65 ('        \n').
```

**Comment by muffinmad** [comment]
Don't remember why `didOpen` was `async`.

Please check recent version.

**Comment by rwols** [comment]
I don't see this happening anymore on 1.5 I think. I'll re-open if it happens again!
