### ISSUE TITLE
Sometimes exception thrown in textDocument/didOpen notification handler

### ISSUE THREAD

**Issue by rwols** [muffinmad/anakin-language-server#9]
```
anakin: INFO:root:  /home/raoul/.local/lib/python3.7/site-packages
anakin: INFO:root:  /usr/local/lib/python3.7/dist-packages
anakin: INFO:root:  /usr/lib/python3/dist-packages
anakin: INFO:root:Jedi project path: /home/raoul/.config/sublime-text-3/Packages/LSP
anakin: ERROR:pygls.protocol:Failed to handle *user defined* notification textDocument/didOpen: <snip>
anakin: Traceback (most recent call last):
anakin:   File "/home/raoul/.local/lib/python3.7/site-packages/pygls/protocol.py", line 60, in decorator
anakin:     self._execute_notification(user_func, *args, **kwargs)
anakin:   File "/home/raoul/.local/lib/python3.7/site-packages/pygls/protocol.py", line 221, in _execute_notification
anakin:     handler(*params)
anakin:   File "/home/raoul/.local/lib/python3.7/site-packages/anakinls/server.py", line 342, in did_open
anakin:     _validate(ls, params.textDocument.uri)
anakin:   File "/home/raoul/.local/lib/python3.7/site-packages/anakinls/server.py", line 321, in _validate
anakin:     PyflakesReporter(result, script, config['pyflakes_errors']))
anakin:   File "/home/raoul/.local/lib/python3.7/site-packages/pyflakes/api.py", line 77, in check
anakin:     reporter.flake(warning)
anakin:   File "/home/raoul/.local/lib/python3.7/site-packages/anakinls/server.py", line 170, in flake
anakin:     if message.__class__.__name__ in self.errors:
anakin: TypeError: argument of type 'bool' is not iterable
```

This is usually for the first file. Further didOpens work OK.

**Comment by rwols** [comment]
I'm on version 1.5.

**Comment by muffinmad** [comment]
I think this is happens during `didChangeConfiguration` because of `pyflykes_errors: true` while `pyflakes_errors` must be the list.

**Comment by rwols** [comment]
You are right.
